version: '3'
services:
  database:
    image: 'postgres:12.0-alpine'
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: docker-example
    ports:
      - "5430:5430"
    command: -p 5430
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
  node-express:
    image: 'node-express:latest'
    ports: 
      - "3000:3000"
    depends_on: 
      - database